M48
; DRILL file KiCad 10.0.1 date 2026-05-03T19:23:28
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-03T19:23:28-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
%
G90
G05
T1
X163.82Y-79.79
X163.82Y-85.57
T2
X128.68Y-113.93
X131.68Y-113.93
X136.43Y-69.855
X139.43Y-69.855
M30
