M48
; DRILL file KiCad 10.0.0 date 2026-04-30T13:09:22
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-30T13:09:22-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
%
G90
G05
T1
X151.14Y-79.36
X151.14Y-85.14
T2
X123.3Y-67.425
X126.3Y-67.425
X135.25Y-67.925
X138.25Y-67.925
M30
